### ISSUE TITLE
検知が多い場合に標準出力が遅い

### ISSUE THREAD

**Issue by nishikawaakira** [YamatoSecurity/RustyBlue#12]
Rusty Blueで大量のログが検知した場合、標準出力に出力するのに時間がかかっているのでなんとかしたい。
バッファリング的なことができれば、OK??
標準出力じゃなくて、ファイル出力にした方がいい?

優先度は低い

**Comment by hitenkoku** [comment]
#10 での対応でいちいちlockを入れて行っていることも要因として挙げられるかもしれません。
他項目がなければこちらを対処しようと思います
