### ISSUE TITLE
check_commandで時間が掛かっているっぽい

### ISSUE THREAD

**Issue by nishikawaakira** [YamatoSecurity/RustyBlue#13]
src/detections/utils.rsのcheck_commandで時間がかかっているっぽい。
正規表現のインスタンスをキャッシュする仕組みをいれても、正規表現の比較にはそれなりに時間がかかっていそう。
他に方法が何かないかどうか

**Comment by hitenkoku** [comment]
https://github.com/YamatoSecurity/RustyBlue/blob/8acfb175441669bea4409a5457ea5799a883053f/src/detections/utils.rs#L52 の部分をif文として先にもっていって、処理が重そうな https://github.com/YamatoSecurity/RustyBlue/blob/8acfb175441669bea4409a5457ea5799a883053f/src/detections/utils.rs#L50 を通る回数をできる限り減らすという小手先の方法はあるかもしれません。
