### ISSUE TITLE
regex.txtのtype：1(Servicename)の場合、設定値チェック処理の調査

### ISSUE THREAD

**Issue by garigariganzy** [YamatoSecurity/RustyBlue#20]

**Comment by garigariganzy** [comment]
regex.txtのtypeが1(Servicename)の設定値の場合、カラム４番目が設定されていますが、４番目があるとutil.rsのcheck_regex()でチェックされない事象があり

**Comment by hitenkoku** [comment]
DeepBlueCLIでの処理部分の個所を確認の上、修正が必要であれば対応。

**Comment by garigariganzy** [comment]
DeepBlueCLIでは、regex.txtを「ConvertFrom-Csv」を利用して、Type:1の行(末尾2行)も読み込んでいることを確認。該当の末尾2行の4つ目のデータは、読み込み自体されていないことを確認。
RustyBlueでは、regex.txtの4つ目のデータを削除することで対応。
